# This file is auto generated. More info: https://github.com/Daivuk/apdoom

from BaseClasses import ItemClassification
from typing import TypedDict, Dict, Set 


class ItemDict(TypedDict, total=False): 
    classification: ItemClassification 
    count: int 
    name: str 
    doom_type: int # Unique numerical id used to spawn the item. -1 is level item, -2 is level complete item. 
    episode: int # Relevant if that item targets a specific level, like keycard or map reveal pickup. 
    map: int 


item_table: Dict[int, ItemDict] = {
    480000: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Shotgun',
             'doom_type': 2001,
             'episode': -1,
             'map': -1},
    480001: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Rocket launcher',
             'doom_type': 2003,
             'episode': -1,
             'map': -1},
    480002: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Plasma gun',
             'doom_type': 2004,
             'episode': -1,
             'map': -1},
    480003: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Chainsaw',
             'doom_type': 2005,
             'episode': -1,
             'map': -1},
    480004: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Chaingun',
             'doom_type': 2002,
             'episode': -1,
             'map': -1},
    480005: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'BFG9000',
             'doom_type': 2006,
             'episode': -1,
             'map': -1},
    480006: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Backpack',
             'doom_type': 8,
             'episode': -1,
             'map': -1},
    480007: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Armor',
             'doom_type': 2018,
             'episode': -1,
             'map': -1},
    480008: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Mega Armor',
             'doom_type': 2019,
             'episode': -1,
             'map': -1},
    480009: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Berserk',
             'doom_type': 2023,
             'episode': -1,
             'map': -1},
    480010: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Invulnerability',
             'doom_type': 2022,
             'episode': -1,
             'map': -1},
    480011: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Partial invisibility',
             'doom_type': 2024,
             'episode': -1,
             'map': -1},
    480012: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Supercharge',
             'doom_type': 2013,
             'episode': -1,
             'map': -1},
    480013: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Medikit',
             'doom_type': 2012,
             'episode': -1,
             'map': -1},
    480014: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of bullets',
             'doom_type': 2048,
             'episode': -1,
             'map': -1},
    480015: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of rockets',
             'doom_type': 2046,
             'episode': -1,
             'map': -1},
    480016: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Box of shotgun shells',
             'doom_type': 2049,
             'episode': -1,
             'map': -1},
    480017: {'classification': ItemClassification.filler,
             'count': 0,
             'name': 'Energy cell pack',
             'doom_type': 17,
             'episode': -1,
             'map': -1},
    480200: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuclear Plant (E1M2) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 2},
    480201: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Toxin Refinery (E1M3) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 3},
    480202: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Toxin Refinery (E1M3) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 3},
    480203: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (E1M4) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 4},
    480204: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (E1M4) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 4},
    480205: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Phobos Lab (E1M5) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 5},
    480206: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Phobos Lab (E1M5) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 5},
    480207: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Central Processing (E1M6) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 6},
    480208: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Central Processing (E1M6) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 6},
    480209: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Central Processing (E1M6) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 6},
    480210: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Computer Station (E1M7) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 7},
    480211: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Computer Station (E1M7) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 7},
    480212: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Computer Station (E1M7) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 7},
    480213: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Military Base (E1M9) - Yellow keycard',
             'doom_type': 6,
             'episode': 1,
             'map': 9},
    480214: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Military Base (E1M9) - Red keycard',
             'doom_type': 13,
             'episode': 1,
             'map': 9},
    480215: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Military Base (E1M9) - Blue keycard',
             'doom_type': 5,
             'episode': 1,
             'map': 9},
    480216: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Deimos Anomaly (E2M1) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 1},
    480217: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Deimos Anomaly (E2M1) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 1},
    480218: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Containment Area (E2M2) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 2},
    480219: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Containment Area (E2M2) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 2},
    480220: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Containment Area (E2M2) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 2},
    480221: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Refinery (E2M3) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 3},
    480222: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Deimos Lab (E2M4) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 4},
    480223: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Deimos Lab (E2M4) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 4},
    480224: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Halls of the Damned (E2M6) - Blue skull key',
             'doom_type': 40,
             'episode': 2,
             'map': 6},
    480225: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Halls of the Damned (E2M6) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 6},
    480226: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Halls of the Damned (E2M6) - Red skull key',
             'doom_type': 38,
             'episode': 2,
             'map': 6},
    480227: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Spawning Vats (E2M7) - Red keycard',
             'doom_type': 13,
             'episode': 2,
             'map': 7},
    480228: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Spawning Vats (E2M7) - Yellow keycard',
             'doom_type': 6,
             'episode': 2,
             'map': 7},
    480229: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Spawning Vats (E2M7) - Blue keycard',
             'doom_type': 5,
             'episode': 2,
             'map': 7},
    480230: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fortress of Mystery (E2M9) - Blue skull key',
             'doom_type': 40,
             'episode': 2,
             'map': 9},
    480231: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fortress of Mystery (E2M9) - Red skull key',
             'doom_type': 38,
             'episode': 2,
             'map': 9},
    480232: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fortress of Mystery (E2M9) - Yellow skull key',
             'doom_type': 39,
             'episode': 2,
             'map': 9},
    480233: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Slough of Despair (E3M2) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 2},
    480234: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Pandemonium (E3M3) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 3},
    480235: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'House of Pain (E3M4) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 4},
    480236: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'House of Pain (E3M4) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 4},
    480237: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'House of Pain (E3M4) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 4},
    480238: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unholy Cathedral (E3M5) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 5},
    480239: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unholy Cathedral (E3M5) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 5},
    480240: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Mt. Erebus (E3M6) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 6},
    480241: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Limbo (E3M7) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 7},
    480242: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Limbo (E3M7) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 7},
    480243: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Limbo (E3M7) - Yellow skull key',
             'doom_type': 39,
             'episode': 3,
             'map': 7},
    480244: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Warrens (E3M9) - Blue skull key',
             'doom_type': 40,
             'episode': 3,
             'map': 9},
    480245: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Warrens (E3M9) - Red skull key',
             'doom_type': 38,
             'episode': 3,
             'map': 9},
    480246: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hell Beneath (E4M1) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 1},
    480247: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hell Beneath (E4M1) - Blue skull key',
             'doom_type': 40,
             'episode': 4,
             'map': 1},
    480248: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Perfect Hatred (E4M2) - Yellow skull key',
             'doom_type': 39,
             'episode': 4,
             'map': 2},
    480249: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Perfect Hatred (E4M2) - Blue skull key',
             'doom_type': 40,
             'episode': 4,
             'map': 2},
    480250: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sever the Wicked (E4M3) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 3},
    480251: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sever the Wicked (E4M3) - Blue skull key',
             'doom_type': 40,
             'episode': 4,
             'map': 3},
    480252: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unruly Evil (E4M4) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 4},
    480253: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'They Will Repent (E4M5) - Yellow skull key',
             'doom_type': 39,
             'episode': 4,
             'map': 5},
    480254: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'They Will Repent (E4M5) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 5},
    480255: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'They Will Repent (E4M5) - Blue skull key',
             'doom_type': 40,
             'episode': 4,
             'map': 5},
    480256: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Against Thee Wickedly (E4M6) - Blue skull key',
             'doom_type': 40,
             'episode': 4,
             'map': 6},
    480257: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Against Thee Wickedly (E4M6) - Yellow skull key',
             'doom_type': 39,
             'episode': 4,
             'map': 6},
    480258: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Against Thee Wickedly (E4M6) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 6},
    480259: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'And Hell Followed (E4M7) - Blue skull key',
             'doom_type': 40,
             'episode': 4,
             'map': 7},
    480260: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'And Hell Followed (E4M7) - Yellow skull key',
             'doom_type': 39,
             'episode': 4,
             'map': 7},
    480261: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'And Hell Followed (E4M7) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 7},
    480262: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unto the Cruel (E4M8) - Yellow skull key',
             'doom_type': 39,
             'episode': 4,
             'map': 8},
    480263: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unto the Cruel (E4M8) - Red skull key',
             'doom_type': 38,
             'episode': 4,
             'map': 8},
    480264: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fear (E4M9) - Yellow skull key',
             'doom_type': 39,
             'episode': 4,
             'map': 9},
    480400: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hangar (E1M1)',
             'doom_type': -1,
             'episode': 1,
             'map': 1},
    480401: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hangar (E1M1) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 1},
    480402: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Hangar (E1M1) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 1},
    480403: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuclear Plant (E1M2)',
             'doom_type': -1,
             'episode': 1,
             'map': 2},
    480404: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Nuclear Plant (E1M2) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 2},
    480405: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Nuclear Plant (E1M2) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 2},
    480406: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Toxin Refinery (E1M3)',
             'doom_type': -1,
             'episode': 1,
             'map': 3},
    480407: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Toxin Refinery (E1M3) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 3},
    480408: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Toxin Refinery (E1M3) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 3},
    480409: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (E1M4)',
             'doom_type': -1,
             'episode': 1,
             'map': 4},
    480410: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Control (E1M4) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 4},
    480411: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Command Control (E1M4) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 4},
    480412: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Phobos Lab (E1M5)',
             'doom_type': -1,
             'episode': 1,
             'map': 5},
    480413: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Phobos Lab (E1M5) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 5},
    480414: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Phobos Lab (E1M5) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 5},
    480415: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Central Processing (E1M6)',
             'doom_type': -1,
             'episode': 1,
             'map': 6},
    480416: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Central Processing (E1M6) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 6},
    480417: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Central Processing (E1M6) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 6},
    480418: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Computer Station (E1M7)',
             'doom_type': -1,
             'episode': 1,
             'map': 7},
    480419: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Computer Station (E1M7) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 7},
    480420: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Computer Station (E1M7) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 7},
    480421: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Phobos Anomaly (E1M8)',
             'doom_type': -1,
             'episode': 1,
             'map': 8},
    480422: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Phobos Anomaly (E1M8) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 8},
    480423: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Phobos Anomaly (E1M8) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 8},
    480424: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Military Base (E1M9)',
             'doom_type': -1,
             'episode': 1,
             'map': 9},
    480425: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Military Base (E1M9) - Complete',
             'doom_type': -2,
             'episode': 1,
             'map': 9},
    480426: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Military Base (E1M9) - Computer area map',
             'doom_type': 2026,
             'episode': 1,
             'map': 9},
    480427: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Deimos Anomaly (E2M1)',
             'doom_type': -1,
             'episode': 2,
             'map': 1},
    480428: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Deimos Anomaly (E2M1) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 1},
    480429: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Deimos Anomaly (E2M1) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 1},
    480430: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Containment Area (E2M2)',
             'doom_type': -1,
             'episode': 2,
             'map': 2},
    480431: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Containment Area (E2M2) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 2},
    480432: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Containment Area (E2M2) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 2},
    480433: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Refinery (E2M3)',
             'doom_type': -1,
             'episode': 2,
             'map': 3},
    480434: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Refinery (E2M3) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 3},
    480435: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Refinery (E2M3) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 3},
    480436: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Deimos Lab (E2M4)',
             'doom_type': -1,
             'episode': 2,
             'map': 4},
    480437: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Deimos Lab (E2M4) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 4},
    480438: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Deimos Lab (E2M4) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 4},
    480439: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Center (E2M5)',
             'doom_type': -1,
             'episode': 2,
             'map': 5},
    480440: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Command Center (E2M5) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 5},
    480441: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Command Center (E2M5) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 5},
    480442: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Halls of the Damned (E2M6)',
             'doom_type': -1,
             'episode': 2,
             'map': 6},
    480443: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Halls of the Damned (E2M6) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 6},
    480444: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Halls of the Damned (E2M6) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 6},
    480445: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Spawning Vats (E2M7)',
             'doom_type': -1,
             'episode': 2,
             'map': 7},
    480446: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Spawning Vats (E2M7) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 7},
    480447: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Spawning Vats (E2M7) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 7},
    480448: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Tower of Babel (E2M8)',
             'doom_type': -1,
             'episode': 2,
             'map': 8},
    480449: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Tower of Babel (E2M8) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 8},
    480450: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Tower of Babel (E2M8) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 8},
    480451: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fortress of Mystery (E2M9)',
             'doom_type': -1,
             'episode': 2,
             'map': 9},
    480452: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fortress of Mystery (E2M9) - Complete',
             'doom_type': -2,
             'episode': 2,
             'map': 9},
    480453: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Fortress of Mystery (E2M9) - Computer area map',
             'doom_type': 2026,
             'episode': 2,
             'map': 9},
    480454: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hell Keep (E3M1)',
             'doom_type': -1,
             'episode': 3,
             'map': 1},
    480455: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hell Keep (E3M1) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 1},
    480456: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Hell Keep (E3M1) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 1},
    480457: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Slough of Despair (E3M2)',
             'doom_type': -1,
             'episode': 3,
             'map': 2},
    480458: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Slough of Despair (E3M2) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 2},
    480459: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Slough of Despair (E3M2) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 2},
    480460: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Pandemonium (E3M3)',
             'doom_type': -1,
             'episode': 3,
             'map': 3},
    480461: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Pandemonium (E3M3) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 3},
    480462: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Pandemonium (E3M3) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 3},
    480463: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'House of Pain (E3M4)',
             'doom_type': -1,
             'episode': 3,
             'map': 4},
    480464: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'House of Pain (E3M4) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 4},
    480465: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'House of Pain (E3M4) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 4},
    480466: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unholy Cathedral (E3M5)',
             'doom_type': -1,
             'episode': 3,
             'map': 5},
    480467: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unholy Cathedral (E3M5) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 5},
    480468: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Unholy Cathedral (E3M5) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 5},
    480469: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Mt. Erebus (E3M6)',
             'doom_type': -1,
             'episode': 3,
             'map': 6},
    480470: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Mt. Erebus (E3M6) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 6},
    480471: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Mt. Erebus (E3M6) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 6},
    480472: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Limbo (E3M7)',
             'doom_type': -1,
             'episode': 3,
             'map': 7},
    480473: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Limbo (E3M7) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 7},
    480474: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Limbo (E3M7) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 7},
    480475: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dis (E3M8)',
             'doom_type': -1,
             'episode': 3,
             'map': 8},
    480476: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Dis (E3M8) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 8},
    480477: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Dis (E3M8) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 8},
    480478: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Warrens (E3M9)',
             'doom_type': -1,
             'episode': 3,
             'map': 9},
    480479: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Warrens (E3M9) - Complete',
             'doom_type': -2,
             'episode': 3,
             'map': 9},
    480480: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Warrens (E3M9) - Computer area map',
             'doom_type': 2026,
             'episode': 3,
             'map': 9},
    480481: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hell Beneath (E4M1)',
             'doom_type': -1,
             'episode': 4,
             'map': 1},
    480482: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Hell Beneath (E4M1) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 1},
    480483: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Hell Beneath (E4M1) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 1},
    480484: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Perfect Hatred (E4M2)',
             'doom_type': -1,
             'episode': 4,
             'map': 2},
    480485: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Perfect Hatred (E4M2) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 2},
    480486: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Perfect Hatred (E4M2) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 2},
    480487: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sever the Wicked (E4M3)',
             'doom_type': -1,
             'episode': 4,
             'map': 3},
    480488: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Sever the Wicked (E4M3) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 3},
    480489: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Sever the Wicked (E4M3) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 3},
    480490: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unruly Evil (E4M4)',
             'doom_type': -1,
             'episode': 4,
             'map': 4},
    480491: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unruly Evil (E4M4) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 4},
    480492: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Unruly Evil (E4M4) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 4},
    480493: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'They Will Repent (E4M5)',
             'doom_type': -1,
             'episode': 4,
             'map': 5},
    480494: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'They Will Repent (E4M5) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 5},
    480495: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'They Will Repent (E4M5) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 5},
    480496: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Against Thee Wickedly (E4M6)',
             'doom_type': -1,
             'episode': 4,
             'map': 6},
    480497: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Against Thee Wickedly (E4M6) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 6},
    480498: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Against Thee Wickedly (E4M6) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 6},
    480499: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'And Hell Followed (E4M7)',
             'doom_type': -1,
             'episode': 4,
             'map': 7},
    480500: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'And Hell Followed (E4M7) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 7},
    480501: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'And Hell Followed (E4M7) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 7},
    480502: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unto the Cruel (E4M8)',
             'doom_type': -1,
             'episode': 4,
             'map': 8},
    480503: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Unto the Cruel (E4M8) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 8},
    480504: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Unto the Cruel (E4M8) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 8},
    480505: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fear (E4M9)',
             'doom_type': -1,
             'episode': 4,
             'map': 9},
    480506: {'classification': ItemClassification.progression,
             'count': 1,
             'name': 'Fear (E4M9) - Complete',
             'doom_type': -2,
             'episode': 4,
             'map': 9},
    480507: {'classification': ItemClassification.filler,
             'count': 1,
             'name': 'Fear (E4M9) - Computer area map',
             'doom_type': 2026,
             'episode': 4,
             'map': 9},
}


item_name_groups: Dict[str, Set[str]] = {
    'Ammos': {'Box of bullets', 'Box of rockets', 'Box of shotgun shells', 'Energy cell pack', },
    'Computer area maps': {'Against Thee Wickedly (E4M6) - Computer area map', 'And Hell Followed (E4M7) - Computer area map', 'Central Processing (E1M6) - Computer area map', 'Command Center (E2M5) - Computer area map', 'Command Control (E1M4) - Computer area map', 'Computer Station (E1M7) - Computer area map', 'Containment Area (E2M2) - Computer area map', 'Deimos Anomaly (E2M1) - Computer area map', 'Deimos Lab (E2M4) - Computer area map', 'Dis (E3M8) - Computer area map', 'Fear (E4M9) - Computer area map', 'Fortress of Mystery (E2M9) - Computer area map', 'Halls of the Damned (E2M6) - Computer area map', 'Hangar (E1M1) - Computer area map', 'Hell Beneath (E4M1) - Computer area map', 'Hell Keep (E3M1) - Computer area map', 'House of Pain (E3M4) - Computer area map', 'Limbo (E3M7) - Computer area map', 'Military Base (E1M9) - Computer area map', 'Mt. Erebus (E3M6) - Computer area map', 'Nuclear Plant (E1M2) - Computer area map', 'Pandemonium (E3M3) - Computer area map', 'Perfect Hatred (E4M2) - Computer area map', 'Phobos Anomaly (E1M8) - Computer area map', 'Phobos Lab (E1M5) - Computer area map', 'Refinery (E2M3) - Computer area map', 'Sever the Wicked (E4M3) - Computer area map', 'Slough of Despair (E3M2) - Computer area map', 'Spawning Vats (E2M7) - Computer area map', 'They Will Repent (E4M5) - Computer area map', 'Tower of Babel (E2M8) - Computer area map', 'Toxin Refinery (E1M3) - Computer area map', 'Unholy Cathedral (E3M5) - Computer area map', 'Unruly Evil (E4M4) - Computer area map', 'Unto the Cruel (E4M8) - Computer area map', 'Warrens (E3M9) - Computer area map', },
    'Keys': {'Against Thee Wickedly (E4M6) - Blue skull key', 'Against Thee Wickedly (E4M6) - Red skull key', 'Against Thee Wickedly (E4M6) - Yellow skull key', 'And Hell Followed (E4M7) - Blue skull key', 'And Hell Followed (E4M7) - Red skull key', 'And Hell Followed (E4M7) - Yellow skull key', 'Central Processing (E1M6) - Blue keycard', 'Central Processing (E1M6) - Red keycard', 'Central Processing (E1M6) - Yellow keycard', 'Command Control (E1M4) - Blue keycard', 'Command Control (E1M4) - Yellow keycard', 'Computer Station (E1M7) - Blue keycard', 'Computer Station (E1M7) - Red keycard', 'Computer Station (E1M7) - Yellow keycard', 'Containment Area (E2M2) - Blue keycard', 'Containment Area (E2M2) - Red keycard', 'Containment Area (E2M2) - Yellow keycard', 'Deimos Anomaly (E2M1) - Blue keycard', 'Deimos Anomaly (E2M1) - Red keycard', 'Deimos Lab (E2M4) - Blue keycard', 'Deimos Lab (E2M4) - Yellow keycard', 'Fear (E4M9) - Yellow skull key', 'Fortress of Mystery (E2M9) - Blue skull key', 'Fortress of Mystery (E2M9) - Red skull key', 'Fortress of Mystery (E2M9) - Yellow skull key', 'Halls of the Damned (E2M6) - Blue skull key', 'Halls of the Damned (E2M6) - Red skull key', 'Halls of the Damned (E2M6) - Yellow skull key', 'Hell Beneath (E4M1) - Blue skull key', 'Hell Beneath (E4M1) - Red skull key', 'House of Pain (E3M4) - Blue skull key', 'House of Pain (E3M4) - Red skull key', 'House of Pain (E3M4) - Yellow skull key', 'Limbo (E3M7) - Blue skull key', 'Limbo (E3M7) - Red skull key', 'Limbo (E3M7) - Yellow skull key', 'Military Base (E1M9) - Blue keycard', 'Military Base (E1M9) - Red keycard', 'Military Base (E1M9) - Yellow keycard', 'Mt. Erebus (E3M6) - Blue skull key', 'Nuclear Plant (E1M2) - Red keycard', 'Pandemonium (E3M3) - Blue skull key', 'Perfect Hatred (E4M2) - Blue skull key', 'Perfect Hatred (E4M2) - Yellow skull key', 'Phobos Lab (E1M5) - Blue keycard', 'Phobos Lab (E1M5) - Yellow keycard', 'Refinery (E2M3) - Blue keycard', 'Sever the Wicked (E4M3) - Blue skull key', 'Sever the Wicked (E4M3) - Red skull key', 'Slough of Despair (E3M2) - Blue skull key', 'Spawning Vats (E2M7) - Blue keycard', 'Spawning Vats (E2M7) - Red keycard', 'Spawning Vats (E2M7) - Yellow keycard', 'They Will Repent (E4M5) - Blue skull key', 'They Will Repent (E4M5) - Red skull key', 'They Will Repent (E4M5) - Yellow skull key', 'Toxin Refinery (E1M3) - Blue keycard', 'Toxin Refinery (E1M3) - Yellow keycard', 'Unholy Cathedral (E3M5) - Blue skull key', 'Unholy Cathedral (E3M5) - Yellow skull key', 'Unruly Evil (E4M4) - Red skull key', 'Unto the Cruel (E4M8) - Red skull key', 'Unto the Cruel (E4M8) - Yellow skull key', 'Warrens (E3M9) - Blue skull key', 'Warrens (E3M9) - Red skull key', },
    'Levels': {'Against Thee Wickedly (E4M6)', 'And Hell Followed (E4M7)', 'Central Processing (E1M6)', 'Command Center (E2M5)', 'Command Control (E1M4)', 'Computer Station (E1M7)', 'Containment Area (E2M2)', 'Deimos Anomaly (E2M1)', 'Deimos Lab (E2M4)', 'Dis (E3M8)', 'Fear (E4M9)', 'Fortress of Mystery (E2M9)', 'Halls of the Damned (E2M6)', 'Hangar (E1M1)', 'Hell Beneath (E4M1)', 'Hell Keep (E3M1)', 'House of Pain (E3M4)', 'Limbo (E3M7)', 'Military Base (E1M9)', 'Mt. Erebus (E3M6)', 'Nuclear Plant (E1M2)', 'Pandemonium (E3M3)', 'Perfect Hatred (E4M2)', 'Phobos Anomaly (E1M8)', 'Phobos Lab (E1M5)', 'Refinery (E2M3)', 'Sever the Wicked (E4M3)', 'Slough of Despair (E3M2)', 'Spawning Vats (E2M7)', 'They Will Repent (E4M5)', 'Tower of Babel (E2M8)', 'Toxin Refinery (E1M3)', 'Unholy Cathedral (E3M5)', 'Unruly Evil (E4M4)', 'Unto the Cruel (E4M8)', 'Warrens (E3M9)', },
    'Powerups': {'Armor', 'Berserk', 'Invulnerability', 'Mega Armor', 'Partial invisibility', 'Supercharge', },
    'Weapons': {'BFG9000', 'Chaingun', 'Chainsaw', 'Plasma gun', 'Rocket launcher', 'Shotgun', },
}
